name: CI/CD Pipelines

on:
    push:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
            
